server:
  port: 8086

spring:
  application:
    name: easypam-notify
    config:
      import:
        - optional:nacos:easypam-notify.yml?server-addr=localhost:8848&namespace=easypam
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/easypam_notify?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root
  data:
    redis:
      host: localhost
      port: 6379
      database: 5
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
        namespace: easypam
      config:
        server-addr: localhost:8848
        namespace: easypam
        file-extension: yml
        import-check:
          enabled: false

rocketmq:
  name-server: localhost:9876
  consumer:
    group: easypam-notify-consumer

mybatis-plus:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
